//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSGTable
    {
        public int MSGID { get; set; }
        public string FromEmail { get; set; }
        public string TOEmail { get; set; }
        public string MSGtext { get; set; }
        public System.DateTime MSGDate { get; set; }
        public System.TimeSpan MSGTime { get; set; }
    }
}
